name: CI
on:
  push:
    branches: 
      - dev
  pull_request:
    branches: 
      - dev
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run script
        run: python GetPlaylistRadarPlot.py --push
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      - name: Commit changes
        run: |
          git config --global user.name 'GitHubActions_CICD'
          git config --global user.email 'michael.barrows.a@gmail.com'
          git commit -am "CICD - Radar Charts"
          git push
