name: CI
on:
  push:
    branches: 
      - dev
  pull_request:
    branches: 
      - dev
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with: 
          auto-update-conda: true
          activate-environment: python3_7client
          python-version: 3.7
      - name: Install dependencies
        run: |
          conda init bash
          source ~/.bashrc
          conda install pip
          conda install -c plotly plotly-orca
          conda install pyyaml
          conda install pandas
          conda install requests
          conda activate python3_7client
      - name: Run script
        run: python GetPlaylistRadarPlot.py --push
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        
